# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Metropolis sampler using Rcpp
#' @description A Metropolis sampler using Rcpp used in homework 12
#' @param N the number of samples
#' @param sd the standard error of the normal distribution
#' @return a random sample of size \code{n}
#' @export
Metropolis_C <- function(N, sd) {
    .Call('_SC19080_Metropolis_C', PACKAGE = 'SC19080', N, sd)
}

